### PR TITLE
Added Placeholder Image

### LINKED ISSUE #2: #INC-5312: Missing image
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

### PR DESCRIPTION
**Pull request by nalin-singh**
# Description

A temporary fix to the image placeholder issue, I have moved the placeholder image inside the imgs folder from the public folder and used it with conditional rendering in the ItemPreview.js component.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks @nalin-singh, I'll review the changes right away!

**Review by ghost — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by ghost — APPROVED** [review]
Excellent job @nalin-singh! You're now able to merge the PR.

**Comment by nalin-singh** [comment]
image

**Pull request merged**
